### ISSUE TITLE
OVH library

### ISSUE THREAD

**Issue by yadutaf** [stephenmoloney/ex_ovh#2]
Hello,

I Work for OVH and maintain github.com/ovh/python-ovh. I love the idea of building a wrapper for Elixir ! If you need any help with the API, feel free to contact me.

Regards,

**Comment by stephenmoloney** [comment]
Thanks yadutaf! 

All going fine for now. :+1: 

I only cover `/cloud` and `/webstorageCDN` for now but it would be very easy to extend it since all the parts are in place to easily extend the API calls and I hope to extend it over time. I also hope to add tests. I already have a full test suite for the `ex_hubic` API in a different REPO (soon to release).

I am also writing a client for Openstack called `Openstex`, it covers only the Swift API and Keystone API though at the moment. Inside the `Openstex` repository, there are adapters that allow for use of `Rackspace Cloudfiles`, `Rackspace CloudfilesCDN`, `Hubic`, `OVH Cloudstorage` or `OVH Webstorage`. 
It's quite easy to add an `adapter` for other providers. 

I'm quite happy with how it is turning out.

Thanks and I'll be sure to get in touch if needed.
